# -*- coding: gbk -*-
mysteel_url_map = {\
    "Taian HRC": {"url": "http://list1.mysteel.com/market/p-231-----010103-0-01010208-------1.html", "mode": "construction",
             "price_name": "泰安市场热轧板卷价格行情", "product": "热轧板卷", "spec": "5.5-11.5*1500*C", "origin": "中铁装备"},
    "Shanghai HRC": {"url": "http://list1.mysteel.com/price/p-10058--010103--1.html", "mode": "hrc", "price_name": None,
             "area": "上海", "spec": "4.75热轧板卷"},
    "Guangzhou HRC": {"url": "http://list1.mysteel.com/price/p-10058--010103--1.html", "mode": "hrc", "price_name": None,
             "area": "广州", "spec": "4.75热轧板卷"},
    "Tianjin HRC": {"url": "http://list1.mysteel.com/price/p-10058--010103--1.html", "mode": "hrc", "price_name": None,
             "area": "天津", "spec": "4.75热轧板卷"},
    "Shanghai CRC": {"url": "http://list1.mysteel.com/price/p-10053--010104--1.html", "mode": "crc", "price_name": None,
             "area": "上海", "spec": "1.0mm"},
    "Guangzhou CRC": {"url": "http://list1.mysteel.com/price/p-10053--010104--1.html", "mode": "crc", "price_name": None,
             "area": "广州", "spec": "1.0mm"},
    "Tianjin CRC": {"url": "http://list1.mysteel.com/price/p-10053--010104--1.html", "mode": "crc", "price_name": None,
             "area": "天津", "spec": "1.0mm"},
    "Shanghai Rebar PingGang": {"url": "http://list1.mysteel.com/market/p-228-15278-----0--------1.html", "mode": "construction",
             "price_name": "上海市场建筑钢材价格行情", "product": "螺纹钢", "spec": "Φ16-22", "origin": "萍钢"},
    "Shanghai Rebar ShenTe": {"url": "http://list1.mysteel.com/market/p-228-15278-----0--------1.html", "mode": "construction",
             "price_name": "上海市场建筑钢材价格行情", "product": "螺纹钢", "spec": "Ф16-25", "origin": "申特"},
    "Shanghai Rebar LianXinHuangHai": {"url": "http://list1.mysteel.com/market/p-228-15278-----0--------1.html", "mode": "construction",
             "price_name": "上海市场建筑钢材价格行情", "product": "螺纹钢", "spec": "Ф16-25", "origin": "联鑫黄海"},
    "Shanghai Rebar LianYunGangXingXin": {"url": "http://list1.mysteel.com/market/p-228-15278-----0--------1.html", "mode": "construction",
             "price_name": "上海市场建筑钢材价格行情", "product": "螺纹钢", "spec": "Ф16-25", "origin": "连云港兴鑫"},
    "Guangzhou Rebar PingGang": {"url": "http://list1.mysteel.com/market/p-228-15584-----0--------1.html", "mode": "construction",
             "price_name": "广州市场建筑钢材价格行情", "product": "螺纹钢", "spec": "Ф18-25", "origin": "萍钢"},
    "Tianjin Rebar DongHua": {"url": "http://list1.mysteel.com/market/p-228-----010101-0-0104-------1.html", "mode": "construction",
             "price_name": "天津市场建筑钢材价格行情", "product": "螺纹钢", "spec": "Ф16", "origin": "东华钢铁"},
    "Tangshan Billet": {"url": "http://list1.mysteel.com/market/p-356-14542-----0--------1.html", "mode": "furnace_raw",
             "price_name": "唐山钢厂方坯价格行情", "product": "方坯", "spec": "150*150", "origin": "安丰(秦皇岛)"},
    "Jiangsu Billet": {"url": "http://list1.mysteel.com/market/p-356-----030701-0-0101-------1.html", "mode": "js_furnace_raw",
             "price_name": "江苏市场方坯价格行情", "product": "150*150", "spec": "Q235", "origin": "长强"},
    "BeiJing Rebar HBIS": {"url": "http://list1.mysteel.com/market/p-228-12911-----0--------1.html", "mode": "construction",
             "price_name": "北京市场建筑钢材价格行情", "product": "螺纹钢", "spec": "Ф18-25", "origin": "河钢宣钢"},
    "BeiJing Rebar DongHua": {"url": "http://list1.mysteel.com/market/p-228-12911-----0--------1.html", "mode": "construction",
             "price_name": "北京市场建筑钢材价格行情", "product": "螺纹钢", "spec": "Ф18-25", "origin": "东华钢铁"},
    "BeiJing Rebar XinXing": {"url": "http://list1.mysteel.com/market/p-228-12911-----0--------1.html", "mode": "construction",
             "price_name": "北京市场建筑钢材价格行情", "product": "螺纹钢", "spec": "Ф16-25", "origin": "新兴铸管"},
    "Tangshan Rebar": {"url": "http://list1.mysteel.com/market/p-228-----010101-0-0104-------1.html", "mode": "construction",
             "price_name": "唐山市场建筑钢材价格行情", "product": "螺纹钢", "spec": "Ф18-25", "origin": "东海特钢"},
    "Tangshan Strip": {"url": "http://list1.mysteel.com/market/p-235-----010108-0-01040302-------1.html", "mode": "furnace_raw",
             "price_name": "唐山钢企145mm热轧带钢出厂价格", "product": "热轧带钢", "spec": "2.5*145", "origin": "金港"},
    "Tangshan Angle steel 50*5": {"url": "http://list1.mysteel.com/market/p-227-----010107-0-0104-------1.html", "mode": "furnace_raw",
             "price_name": "唐山市场角钢价格行情", "product": "等边角钢", "spec": "5#", "origin": "唐山正丰"},
    "Tangshan Channel steel 16#": {"url": "http://list1.mysteel.com/market/p-227-----010107-0-0104-------1.html", "mode": "furnace_raw",
             "price_name": "唐山市场槽钢价格行情", "product": "槽钢", "spec": "16#", "origin": "唐山瑞兴"},
    "Tangshan I beam steel 16#": {"url": "http://list1.mysteel.com/market/p-227-----010107-0-0104-------1.html", "mode": "furnace_raw",
             "price_name": "唐山市场工字钢价格行情", "product": "工字钢", "spec": "16#-18#", "origin": "唐山国鑫"},
    "ShangHai Bengang SPHC": {"url": "http://list1.mysteel.com/market/p-231-----010103-0-010101-------1.html", "mode": "construction",
             "price_name": "上海市场热轧板卷价格行情", "product": "SPHC", "spec": "2.75*1250*C", "origin": "鞍钢/本钢"},
    "Lecong Chenggang SPHC": {"url": "http://list1.mysteel.com/market/p-231-----010103-0-0102010803-------1.html",
             "mode": "construction", "price_name": "乐从市场热轧板卷价格行情", "product": "SPHC", "spec": "3.0*1250*C", "origin": "承钢"},
    "Tangshan Coking Coal": {"url": "http://list.coal.glinfo.com/price/p-10043--050202--1.html", "mode": "coal",
             "price_name": "全国主要城市炼焦煤价格汇总", "area": "唐山"},
    "Tangshan Coke": {"url": "http://list1.mysteel.com/price/p-10039--050101--1.html", "mode": "coal",
             "price_name": "全国主要城市冶金焦价格汇总", "area": "唐山"}
}

mysteel_excel_columns ={"Taian HRC": {"PM": "AO", "AM": "AL"},
                "Shanghai HRC": {"PM": "F", "AM": "F"},
                "Guangzhou HRC": {"PM": "G", "AM": "G"},
                "Tianjin HRC": {"PM": "H", "AM": "H"},
                "Shanghai CRC": {"PM": "I", "AM": "I"},
                "Guangzhou CRC": {"PM": "J", "AM": "J"},
                "Tianjin CRC": {"PM": "K", "AM": "K"},
                "Shanghai Rebar PingGang": {"PM": "B", "AM": "B"},
                "Shanghai Rebar ShenTe": {"PM": "T", "AM": "P"},
                "Shanghai Rebar LianXinHuangHai": {"PM": "U", "AM": "Q"},
                "Shanghai Rebar LianYunGangXingXin": {"PM": "V", "AM": "R"},
                "Guangzhou Rebar PingGang": {"PM": "D", "AM": "D"},
                "Tianjin Rebar DongHua": {"PM": "E", "AM": "DE"},
                "Tangshan Billet": {"PM": "O", "AM": "O"},
                "Jiangsu Billet": {"PM": "AF", "AM": "X"},
                "BeiJing Rebar HBIS": {"PM": "AG", "AM": "Y"},
                "BeiJing Rebar DongHua": {"PM": "AJ", "AM": "AH"},
                "BeiJing Rebar XinXing": {"PM": "AK", "AM": "AI"},
                "Tangshan Rebar": {"PM": "W", "AM": "S"},
                "Tangshan Strip": {"PM": "X", "AM": "T"},
                "Tangshan Angle steel 50*5": {"PM": "Y",  "AM": "U"},
                "Tangshan Channel steel 16#": {"PM": "Z",  "AM": "V"},
                "Tangshan I beam steel 16#":  {"PM": "AA",  "AM": "W"},
                "ShangHai Bengang SPHC": {"PM": "AU"},
                "Lecong Chenggang SPHC": {"PM": "AR"},
                "Tangshan Coking Coal": {"PM": "AH"},
                "Tangshan Coke": {"PM": "AI"},
}

